version: '3.9'


services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - django
    restart: always
    networks:
      - django-network
    ports:
      - ${ENGINX_PORT}
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - django-network
    command: >
      bash -c "python3 manage.py migrate &&
               python3 manage.py create_admin &&
               python3 manage.py runserver 0.0.0.0:8000"

  file_storage:
    build:
      context: FileStorageService
      dockerfile: Dockerfile
    restart: always
    networks:
      - django-network
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgstore:/var/lib/postgresql/data
    networks:
      - django-network
    env_file:
      - .env

volumes:
  pgstore:

networks:
  django-network:
    driver: bridge
